name: 'Terraform'

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    terraform:
        name: 'Terraform'
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.PR_AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.PR_AWS_SECRET_ACCESS_KEY }}

            - name: Terraform Init
              run: terraform init infra

            - name: Terraform Format
              run: terraform fmt infra -check

            - name: Terraform Plan
              run: terraform plan infra

            - name: Terraform Apply
              if: github.ref == 'refs/heads/main' && github.event_name == 'push'
              run: terraform apply infra -auto-approve
